# Generated by Django 3.2 on 2021-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_form_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('select_type', models.TextField(choices=[('friends', 'Friends.'), ('search engine', 'Search engine.'), ('add', 'Add.')])),
                ('news', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
    ]
