# Generated by Django 3.2.5 on 2021-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_custom_form_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_form_modal',
            name='select_type',
            field=models.CharField(max_length=20),
        ),
    ]
